services:
  postgres:
    image: postgres:15
    container_name: fairshare-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fairshare
      POSTGRES_USER: fairuser
      POSTGRES_PASSWORD: fairpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fairuser -d fairshare"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.27.0
    container_name: fairshare-liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/changelogs:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://postgres:5432/fairshare
      --changeLogFile=changelog/0001_add_init.sql
      --username=fairuser
      --password=fairpass
      --logLevel=INFO
      update
    restart: "no"

  app:
    build: .
    container_name: fairshare-app
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fairshare
      SPRING_DATASOURCE_USERNAME: fairuser
      SPRING_DATASOURCE_PASSWORD: fairpass
      SPRING_LIQUIBASE_ENABLED: "false"  # Disabled since Liquibase runs separately
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    restart: on-failure

volumes:
  pgdata: