spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fairshare
    username: fairuser
    password: fairpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false

