-- liquibase formatted sql

-- changeset codespace:1751125148242-1
ALTER TABLE expense ADD split_mode VARCHAR(255);

-- changeset codespace:1751125148242-2
ALTER TABLE expense DROP COLUMN "splitMode";

-- liquibase formatted sql

-- changeset DELL:1751174684766-1
CREATE SEQUENCE  IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 1;

-- changeset DELL:1751174684766-2
CREATE TABLE expense (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53), description VARCHAR(255), split_mode VARCHAR(255), group_id UUID, payer_id BIGINT, CONSTRAINT "expensePK" PRIMARY KEY (id));

-- changeset DELL:1751174684766-3
CREATE TABLE expense_participants (expense_id BIGINT NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751174684766-4
CREATE TABLE expense_split (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53) NOT NULL, expense_id BIGINT, user_id BIGINT, CONSTRAINT "expense_splitPK" PRIMARY KEY (id));

-- changeset DELL:1751174684766-5
CREATE TABLE group_members (group_id UUID NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751174684766-6
CREATE TABLE user_group (id UUID NOT NULL, group_name VARCHAR(255) NOT NULL, created_by BIGINT NOT NULL, CONSTRAINT "user_groupPK" PRIMARY KEY (id));

-- changeset DELL:1751174684766-7
CREATE TABLE users (id BIGINT NOT NULL, email VARCHAR(150) NOT NULL, user_name VARCHAR(100) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset DELL:1751174684766-8
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset DELL:1751174684766-9
ALTER TABLE expense_split ADD CONSTRAINT "FK49aqcwgxuxn9jtbac7m8nrimq" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751174684766-10
ALTER TABLE group_members ADD CONSTRAINT "FKa0rnvuit5l8opskad2n72w9ki" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751174684766-11
ALTER TABLE expense_participants ADD CONSTRAINT "FKbt1naml92d64c1w07hjec43sv" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174684766-12
ALTER TABLE expense_split ADD CONSTRAINT "FKl1gujhxin9bs0sluiqggjsu70" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174684766-13
ALTER TABLE expense_participants ADD CONSTRAINT "FKm7slm2xwmymhhadsv70bjj93c" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751174684766-14
ALTER TABLE group_members ADD CONSTRAINT "FKnr9qg33qt2ovmv29g4vc3gtdx" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174684766-15
ALTER TABLE expense ADD CONSTRAINT "FKpa771m9m65s3gt9xf14g6iy97" FOREIGN KEY (payer_id) REFERENCES users (id);

-- changeset DELL:1751174684766-16
ALTER TABLE expense ADD CONSTRAINT "FKstkm8i36yjr56uy251j3hqcko" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751174684766-17
ALTER TABLE user_group ADD CONSTRAINT fk_created_by_user FOREIGN KEY (created_by) REFERENCES users (id);

-- liquibase formatted sql

-- changeset DELL:1751174837733-1
CREATE SEQUENCE  IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 1;

-- changeset DELL:1751174837733-2
CREATE TABLE expense (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53), description VARCHAR(255), split_mode VARCHAR(255), group_id UUID, payer_id BIGINT, CONSTRAINT "expensePK" PRIMARY KEY (id));

-- changeset DELL:1751174837733-3
CREATE TABLE expense_participants (expense_id BIGINT NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751174837733-4
CREATE TABLE expense_split (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53) NOT NULL, expense_id BIGINT, user_id BIGINT, CONSTRAINT "expense_splitPK" PRIMARY KEY (id));

-- changeset DELL:1751174837733-5
CREATE TABLE group_members (group_id UUID NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751174837733-6
CREATE TABLE user_group (id UUID NOT NULL, group_name VARCHAR(255) NOT NULL, created_by BIGINT NOT NULL, CONSTRAINT "user_groupPK" PRIMARY KEY (id));

-- changeset DELL:1751174837733-7
CREATE TABLE users (id BIGINT NOT NULL, email VARCHAR(150) NOT NULL, user_name VARCHAR(100) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset DELL:1751174837733-8
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset DELL:1751174837733-9
ALTER TABLE expense_split ADD CONSTRAINT "FK49aqcwgxuxn9jtbac7m8nrimq" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751174837733-10
ALTER TABLE group_members ADD CONSTRAINT "FKa0rnvuit5l8opskad2n72w9ki" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751174837733-11
ALTER TABLE expense_participants ADD CONSTRAINT "FKbt1naml92d64c1w07hjec43sv" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174837733-12
ALTER TABLE expense_split ADD CONSTRAINT "FKl1gujhxin9bs0sluiqggjsu70" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174837733-13
ALTER TABLE expense_participants ADD CONSTRAINT "FKm7slm2xwmymhhadsv70bjj93c" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751174837733-14
ALTER TABLE group_members ADD CONSTRAINT "FKnr9qg33qt2ovmv29g4vc3gtdx" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751174837733-15
ALTER TABLE expense ADD CONSTRAINT "FKpa771m9m65s3gt9xf14g6iy97" FOREIGN KEY (payer_id) REFERENCES users (id);

-- changeset DELL:1751174837733-16
ALTER TABLE expense ADD CONSTRAINT "FKstkm8i36yjr56uy251j3hqcko" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751174837733-17
ALTER TABLE user_group ADD CONSTRAINT fk_created_by_user FOREIGN KEY (created_by) REFERENCES users (id);

-- liquibase formatted sql

-- changeset DELL:1751175683976-1
CREATE SEQUENCE  IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 1;

-- changeset DELL:1751175683976-2
CREATE TABLE expense (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53), description VARCHAR(255), split_mode VARCHAR(255), group_id UUID, payer_id BIGINT, CONSTRAINT "expensePK" PRIMARY KEY (id));

-- changeset DELL:1751175683976-3
CREATE TABLE expense_participants (expense_id BIGINT NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751175683976-4
CREATE TABLE expense_split (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount FLOAT(53) NOT NULL, expense_id BIGINT, user_id BIGINT, CONSTRAINT "expense_splitPK" PRIMARY KEY (id));

-- changeset DELL:1751175683976-5
CREATE TABLE group_members (group_id UUID NOT NULL, user_id BIGINT NOT NULL);

-- changeset DELL:1751175683976-6
CREATE TABLE user_group (id UUID NOT NULL, group_name VARCHAR(255) NOT NULL, created_by BIGINT NOT NULL, CONSTRAINT "user_groupPK" PRIMARY KEY (id));

-- changeset DELL:1751175683976-7
CREATE TABLE users (id BIGINT NOT NULL, email VARCHAR(150) NOT NULL, user_name VARCHAR(100) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset DELL:1751175683976-8
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset DELL:1751175683976-9
ALTER TABLE expense_split ADD CONSTRAINT "FK49aqcwgxuxn9jtbac7m8nrimq" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751175683976-10
ALTER TABLE group_members ADD CONSTRAINT "FKa0rnvuit5l8opskad2n72w9ki" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751175683976-11
ALTER TABLE expense_participants ADD CONSTRAINT "FKbt1naml92d64c1w07hjec43sv" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751175683976-12
ALTER TABLE expense_split ADD CONSTRAINT "FKl1gujhxin9bs0sluiqggjsu70" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751175683976-13
ALTER TABLE expense_participants ADD CONSTRAINT "FKm7slm2xwmymhhadsv70bjj93c" FOREIGN KEY (expense_id) REFERENCES expense (id);

-- changeset DELL:1751175683976-14
ALTER TABLE group_members ADD CONSTRAINT "FKnr9qg33qt2ovmv29g4vc3gtdx" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset DELL:1751175683976-15
ALTER TABLE expense ADD CONSTRAINT "FKpa771m9m65s3gt9xf14g6iy97" FOREIGN KEY (payer_id) REFERENCES users (id);

-- changeset DELL:1751175683976-16
ALTER TABLE expense ADD CONSTRAINT "FKstkm8i36yjr56uy251j3hqcko" FOREIGN KEY (group_id) REFERENCES user_group (id);

-- changeset DELL:1751175683976-17
ALTER TABLE user_group ADD CONSTRAINT fk_created_by_user FOREIGN KEY (created_by) REFERENCES users (id);

